parallel_es:
	asy hash_table.asy -f png
	pandoc -t beamer -fmarkdown-implicit_figures parallel_es.md -o parallel_es.pdf
abridged_es:
	asy hash_table.asy -f png
	pandoc -t beamer -fmarkdown-implicit_figures abridged_es.md -o abridged_es.pdf
